### ISSUE TITLE
Feature Request: Ability to change current operation for user

### ISSUE THREAD

**Issue by rpgmaster280** [MythicMeta/Mythic_Scripting#2]
I was thinking something along the lines of the code below (except maybe with strings instead of ints):

```
async def set_operation_current_for_operator(
    mythic: mythic_classes.Mythic,
    operator_id: int,
    operation_id: int
):
    """
    Sets the specified operation as current for the specified user.
    """
    query = """
	mutation updateCurrentOpertionMutation($operator_id: Int!, $operation_id: Int!) {
		updateCurrentOperation(user_id: $operator_id, operation_id: $operation_id) {
			status
			error
			operation_id
			__typename
		}
	}
    """
    results = await mythic_utilities.graphql_post(
        mythic=mythic,
        query=query,
        variables={"operator_id": operator_id, "operation_id": operation_id},
    )
    return results["updateCurrentOperation"]
```

The query above was captured from the Mythic GUI frontend whenever I changed operations for my current user. The server returns success when I use this function, but the target user does not appear to switch current engagements. User input is as follows:

```
resp = await mythic.set_operation_current_for_operator(mythic=mythic_instance,operator_id=2,operation_id=3)
print(resp)
```

Response from the server is as follows:

```
{'status': 'success', 'operation_id': 3, '__typename': 'updateCurrentOperationOutput'}
```

I'm not very familiar with graphql (will try to read up on it after the holiday weekend) so it's difficult to troubleshoot the issue. There also might be a way to do it with the current logic, but I didn't see anything from a cursory look. Thank you again for your time and consideration.

**Comment by its-a-feature** [comment]
Hey! Great question! So, that mutation _is_ actually updating the user's current operation; however, you're just not going to see it in the UI currently until you log out and log back in. I'm still working on how to get that data to propagate, but essentially what's happening is:

- When you log in, the React UI gets some information about the user and saves it locally to update the UI and track your current operation
- When you interact with Mythic through the React UI, you send along your JWT to the GraphQL engine ,which forwards it to Mythic. 
- Mythic validates it and adds some headers about your user's current state (current operation, what operations you're in, etc), then sends it back to the GraphQL engine
- The GraphQL engine uses this updated information to make a decision about what you can/can't do and processes your request
- The GraphQL engine then responds back to the React UI

So, when we update the current operation through the ReactUI, I just return an extra piece of information (operation_id) so that the local storage for the ReactUI can update and reflect that your current operation changed. When you do this through the scripting though, the UI doesn't see the update. However, as you saw with the status, it _does_ actually update. So, if you log out and log back in, you'll see that the operation did change. 

I'm still working on a good way to get that information reflected back to the UI though if the change happens outside of the UI. I think the same scenario would happen if you were logged into two browsers at once and updated the current operation in one of them - the other one wouldn't reflect the updated change until you log out and log back in.

**Comment by its-a-feature** [comment]
Ok, I just updated Mythic with a way to help with this. Now, when you go to each page, Mythic UI will do an additional check against the back-end to get information about your current operation. If it doesn't match what it currently has, Mythic will update the UI to reflect the change. This should address the issues you were seeing

**Comment by rpgmaster280** [comment]
Awesome, thank you =)
