### ISSUE TITLE
Apfell build with all_commands=True on 0.0.33 appears broken

### ISSUE THREAD

**Issue by ret2binsh** [MythicMeta/Mythic_Scripting#3]
https://github.com/MythicMeta/Mythic_Scripting/blob/f1082dd71bdecdf4a36d0b8f6c5576b3bc67c606/mythic/mythic_rest.py#L2165

I'm tagging this section since it is where the issue is on Pypi version 0.0.33 but I couldn't find that version within this repo. Hopefully this is the correct place to post the issue.

On the newest pip install for mythic version 0.0.33, building a new Apfell agent with all_commands=True results in an empty command list. It appears that there was a change from handling the exception and appending the command anyways to now simply performing a pass. Not sure if that is intended but it broke the build script that I was using with a modified version of D00mfist's mystikal. After replacing that line with appending the command on exception, I was able to restore the previous behavior. Just wanted to give a heads up in case this is not intended.

**Comment by its-a-feature** [comment]
Good catch! The crux of the issue was actually that I was returning already parsed JSON and trying to parse it again, which caused the exception to be hit. I updated the pypi version to 0.0.34 (and updated the codebase here) to reflect this and fix it. I also added an `include_all_commands` flag to the graphql version if you wanted to start using that suite since we'll be moving towards that eventually
